name: Publish

on:
  workflow_dispatch:
    inputs:
      bom:
        description: 'Publish the BOM Module'
        required: true
        type: boolean
      backup:
        description: 'Publish the Backup Module'
        required: false
        type: boolean
      core:
        description: 'Publish the Core Module'
        required: false
        type: boolean
      data:
        description: 'Publish the Data Module'
        required: false
        type: boolean
      firebase:
        description: 'Publish the Firebase Module'
        required: false
        type: boolean
      framework:
        description: 'Publish the Framework Module'
        required: false
        type: boolean
      monetisation:
        description: 'Publish the Monetisation Module'
        required: false
        type: boolean
      navigation:
        description: 'Publish the Navigation Module'
        required: false
        type: boolean
      screen:
        description: 'Publish the Screen Module'
        required: false
        type: boolean
      ui:
        description: 'Publish the UI Module'
        required: false
        type: boolean

jobs:
  publish:
    name: Snapshot build and publish
    runs-on: ubuntu-latest
    environment: PRODUCTION
    timeout-minutes: 120
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      SONATYPE_CONNECT_TIMEOUT_SECONDS: 120
      SONATYPE_CLOSE_TIMEOUT_SECONDS: 1800

    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Publish BOM
        env:
          BOM_PUBLISH: ${{ github.event.inputs.bom }}
        run: |
          if [[ $BOM_PUBLISH == true ]]; then
            ./gradlew :bom:publish --no-configuration-cache
          fi

      - name: Publish specified modules
        env:
          UI_PUBLISH: ${{ github.event.inputs.ui }}
          CORE_PUBLISH: ${{ github.event.inputs.core }}
        run: |
          modules_to_publish=""

          if [[ $UI_PUBLISH == true ]]; then
            modules_to_publish+="ui"
          fi

          if [[ $CORE_PUBLISH == true ]]; then
            modules_to_publish+="core"
          fi

          if [[ -z "$modules_to_publish" ]]; then
            echo "No modules specified for publishing."
          else
            for module in $modules_to_publish; do
              echo "Publishing module: $module"
              ./gradlew ":${module}:publish" --no-configuration-cache
            done
          fi

      - name: Publish specified modules
        env:
          MODULES: ${{ github.event.inputs.modules }}
        run: |
          if [[ -z "$MODULES" ]]; then
            echo "No modules specified for publishing. Please set the MODULES environment variable."
            exit 1
          fi

          for module in $MODULES; do
            echo "Publishing module: $module"
            ./gradlew ":${module}:publish" --no-configuration-cache
          done
