name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Snapshot build and publish
    runs-on: ubuntu-latest
    environment: PRODUCTION
    timeout-minutes: 120
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      SONATYPE_CONNECT_TIMEOUT_SECONDS: 120
      SONATYPE_CLOSE_TIMEOUT_SECONDS: 1800

    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant Permission to Execute Gradle
        run: chmod +x gradlew

      - name: Publish to MavenCentral
        run: |
          ./gradlew :bom:publish --no-configuration-cache
          ./gradlew :backup:publish --no-configuration-cache
          ./gradlew :core:publish --no-configuration-cache
          ./gradlew :data:publish --no-configuration-cache
          ./gradlew :firebase:publish --no-configuration-cache
          ./gradlew :framework:publish --no-configuration-cache
          ./gradlew :monetisation:publish --no-configuration-cache
          ./gradlew :navigation:publish --no-configuration-cache
          ./gradlew :screen:publish --no-configuration-cache
          ./gradlew :ui:publish --no-configuration-cache
